CREATE DATABASE ATIV3;  

USE ATIV3;  

CREATE TABLE REGION  
(  
    REG_INT_ID INT NOT NULL IDENTITY(1,1),  
    REG_STR_DESC VARCHAR(50) NOT NULL,  

    CONSTRAINT PK_REGION_ID PRIMARY KEY(REG_INT_ID) 
); 


CREATE TABLE STATE 
(  
    STA_INT_ID INT NOT NULL IDENTITY(1,1),  
    REG_INT_ID INT NOT NULL, 
    STA_STR_DESC VARCHAR(70) NOT NULL,  
    STA_STR_SIGLA CHAR(2),  

    CONSTRAINT PK_STATE_ID PRIMARY KEY(STA_INT_ID),
	CONSTRAINT FK_STATE_REGION_ID FOREIGN KEY(REG_INT_ID) REFERENCES REGION(REG_INT_ID)
);  


CREATE TABLE CITY( 
    CIT_INT_ID INT NOT NULL IDENTITY(1,1), 
    STA_INT_ID INT NOT NULL, 
    CIT_STR_DESC VARCHAR(70), 

    CONSTRAINT PK_CITY_ID PRIMARY KEY(CIT_INT_ID),
	CONSTRAINT  FK_CITY_STATE_ID FOREIGN KEY(STA_INT_ID) REFERENCES STATE(STA_INT_ID)
); 

CREATE TABLE PEOPLE 
( 
    PEO_INT_ID INT NOT NULL IDENTITY(1,1), 
    CIT_INT_ID INT NOT NULL, 
    PEO_STR_NOME VARCHAR(70) NOT NULL,  
    PEO_STR_CPF CHAR(11) NOT NULL,  

    CONSTRAINT PK_PEOPLE_ID PRIMARY KEY(PEO_INT_ID), 
    CONSTRAINT UK_PEOPLE_CPF UNIQUE(PEO_STR_CPF),
	CONSTRAINT FK_PEOPLE_CITY_ID FOREIGN KEY(CIT_INT_ID) REFERENCES CITY(CIT_INT_ID)
);  

/* inserindo as regiões*/
INSERT INTO REGION (REG_STR_DESC) VALUES ('Sudeste');
INSERT INTO REGION (REG_STR_DESC) VALUES ('Sul');
INSERT INTO REGION (REG_STR_DESC) VALUES ('Centro-oeste');
INSERT INTO REGION (REG_STR_DESC) VALUES ('Nordeste');
INSERT INTO REGION (REG_STR_DESC) VALUES ('Norte');

/*inserindo os estados com suas respectivas siglas*/
INSERT INTO STATE (STA_STR_DESC, STA_STR_SIGLA, REG_INT_ID) VALUES ('São Paulo','SP',1);
INSERT INTO STATE (STA_STR_DESC, STA_STR_SIGLA, REG_INT_ID) VALUES ('Paraná','PR',2);
INSERT INTO STATE (STA_STR_DESC, STA_STR_SIGLA, REG_INT_ID) VALUES ('Goiás','GO',3);
INSERT INTO STATE (STA_STR_DESC, STA_STR_SIGLA, REG_INT_ID) VALUES ('Sergipe','SE',4);
INSERT INTO STATE (STA_STR_DESC, STA_STR_SIGLA, REG_INT_ID) VALUES ('Acre','AC',5);

