INSERT INTO STATE (STA_STR_DESC, STA_STR_SIGLA, REG_INT_ID ) VALUES
('São Paulo', 'SP', 1),
('Rio de Janeiro', 'RJ', 1),
('Espírito Santo', 'ES', 1),
('Minas Gerais', 'MG', 1),
('Paraná', 'PR', 2),
('Rio Grande do Sul', 'RS', 2),
('Santa Catarina', 'SC', 2),
('Goiás', 'GO', 3),
('Mato Grosso', 'MT', 3),
('Mato Grosso do Sul', 'MS', 3),
('Alagoas', 'AL', 4),
('Bahia', 'BA', 4),
('Ceará', 'CE', 4),
('Maranhão', 'MA', 4),
('Pernambuco', 'PE', 4),
('Paraíba', 'PB', 4),
('Piauí', 'PI', 4),
('Rio Grande do Norte', 'RN', 4),
('Sergipe', 'SE', 4),
('Acre', 'AC', 5),
('Amapá', 'AP', 5),
('Amazonas', 'AM', 5),
('Pará', 'PA', 5),
('Rondônia', 'RO', 5),
('Roraima', 'RR', 5),
('Tocantins', 'TO', 5);

/* REGIOES sudeste=1, sul=2, centro-oeste=3, nordeste=4, norte=5*/